### ISSUE TITLE
How to generate equivalent NequIP model in JAX-MD

### ISSUE THREAD

**Issue by ipcamit** [jax-md/jax-md#313]
I want to try JAX based Nequip model for comparison to torch based one, but I could not get equivalent model. Can someone help on how to get exact same model in JAX-MD?

This is the configuration in NequIP torch:
```
# network
r_max: 4.0
num_layers: 3
l_max: 1
parity: true
num_features: 32
nonlinearity_type: gate

nonlinearity_scalars:
  e: silu
  o: tanh

nonlinearity_gates:
  e: silu
  o: tanh

num_basis: 8
BesselBasis_trainable: true
PolynomialCutoff_p: 6

# radial network
invariant_layers: 2
invariant_neurons: 64
avg_num_neighbors: 16
use_sc: true
```

I have tried the following configuration in `model_from_config` function,

```
graph_net_steps: 3
hidden_irreps: 32x0e + 32x1o
n_elements: 1
n_neighbors: 16.0
nonlinearities:
  e: relu
  o: tanh
num_basis: 8
r_max: 4.0
radial_net_n_hidden: 64
radial_net_n_layers: 2
radial_net_nonlinearity: relu
scalar_mlp_std: 4.0
sh_irreps: 1x0e + 1x1o
use_sc: true
```

The Nequip model has following layer config:
```
RescaleOutput(
  (model): GradientOutput(
    (func): SequentialGraphNetwork(
      (one_hot): OneHotAtomEncoding()
      (spharm_edges): SphericalHarmonicEdgeAttrs(
        (sh): SphericalHarmonics()
      )
      (radial_basis): RadialBasisEdgeEncoding(
        (basis): BesselBasis()
        (cutoff): PolynomialCutoff()
      )
      (chemical_embedding): AtomwiseLinear(
        (linear): Linear(1x0e -> 32x0e | 32 weights)
      )
      (layer0_convnet): ConvNetLayer(
        (equivariant_nonlin): Gate (64x0e+32x1o -> 32x0e+32x1o)
        (conv): InteractionBlock(
          (linear_1): Linear(32x0e -> 32x0e | 1024 weights)
          (fc): FullyConnectedNet[8, 64, 64, 64]
          (tp): TensorProduct(32x0e x 1x0e+1x1o -> 32x0e+32x1o | 64 paths | 64 weights)
          (linear_2): Linear(32x0e+32x1o -> 64x0e+32x1o | 3072 weights)
          (sc): FullyConnectedTensorProduct(32x0e x 1x0e -> 64x0e+32x1o | 2048 paths | 2048 weights)
        )
      )
      (layer1_convnet): ConvNetLayer(
        (equivariant_nonlin): Gate (96x0e+32x1o+32x1e -> 32x0e+32x1e+32x1o)
        (conv): InteractionBlock(
          (linear_1): Linear(32x0e+32x1o -> 32x0e+32x1o | 2048 weights)
          (fc): FullyConnectedNet[8, 64, 64, 160]
          (tp): TensorProduct(32x0e+32x1o x 1x0e+1x1o -> 64x0e+64x1o+32x1e | 160 paths | 160 weights)
          (linear_2): Linear(64x0e+64x1o+32x1e -> 96x0e+32x1o+32x1e | 9216 weights)
          (sc): FullyConnectedTensorProduct(32x0e+32x1o x 1x0e -> 96x0e+32x1o+32x1e | 4096 paths | 4096 weights)
        )
      )
      (layer2_convnet): ConvNetLayer(
        (equivariant_nonlin): Gate (32x0o+96x0e+32x1o+32x1e -> 32x0e+32x0o+32x1e+32x1o)
        (conv): InteractionBlock(
          (linear_1): Linear(32x0e+32x1e+32x1o -> 32x0e+32x1e+32x1o | 3072 weights)
          (fc): FullyConnectedNet[8, 64, 64, 256]
          (tp): TensorProduct(32x0e+32x1e+32x1o x 1x0e+1x1o -> 32x0o+64x0e+96x1o+64x1e | 256 paths | 256 weights)
          (linear_2): Linear(32x0o+64x0e+96x1o+64x1e -> 32x0o+96x0e+32x1o+32x1e | 12288 weights)
          (sc): FullyConnectedTensorProduct(32x0e+32x1e+32x1o x 1x0e -> 32x0o+96x0e+32x1o+32x1e | 5120 paths | 5120 weights)
        )
      )
      (conv_to_output_hidden): AtomwiseLinear(
        (linear): Linear(32x0e+32x0o+32x1e+32x1o -> 16x0e | 512 weights)
      )
      (output_hidden_to_scalar): AtomwiseLinear(
        (linear): Linear(16x0e -> 1x0e | 16 weights)
      )
      (per_species_rescale): PerSpeciesScaleShift()
      (total_energy_sum): AtomwiseReduce()
    )
  )
)
```
